services:
  db:
    image: postgres:17.6-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_store
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - db
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./frontend/Dockerfile
  #   environment:
  #     API_URL: http://backend:8000
  #   env_file:
  #     - .env.local
  #   ports:
  #     - "3000:3000"
volumes:
  db_data:

